##name: Java CI with Maven
##
##permissions:
##  contents: write
##  security-events: write
##
##on:
##  push:
##    branches: [ "main" ]
##  pull_request:
##    branches: [ "main" ]
##
##jobs:
##  build:
##    runs-on: ubuntu-latest
##
##    steps:
##      - uses: actions/checkout@v4
##
##      - name: Set up JDK 17
##        uses: actions/setup-java@v4
##        with:
##          java-version: '17'
##          distribution: 'temurin'
##          cache: maven
##
##      - name: Build with Maven
##        run: mvn -B package -DskipTests --file pom.xml
##
#
#name: Java CI/CD with Docker
#
#on:
#  push:
#    branches: [ "main" ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#
#      - name: Build with Maven
#        run: mvn -B package -DskipTests --file pom.xml
#
#  docker:
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build Docker image
#        run: docker build -t bayetalla/backend-musee-hub:latest .
#
#      - name: Push Docker image
#        run: docker push bayetalla/backend-musee-hub:latest
